apiVersion: apps/v1
kind: Deployment
metadata:
  name: ongoing-project
  namespace: ongprj
  labels:
    app: ongoing-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ongoing-project
  template:
    metadata:
      labels:
        app: ongoing-project
    spec:
      containers:
      - name: ongoing-project-itay
        image: 259826285692.dkr.ecr.eu-central-1.amazonaws.com/ongoing-project-itay:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9000
          protocol: TCP
        resources:
          requests:
            memory: "200Mi"
            cpu: 0.5
          limits:
            memory: "400Mi"
            cpu: 1.0
      imagePullSecrets:
      - name: ecrkey

