apiVersion: v1
kind: Service
metadata:
  name: ongoing-project
  namespace: ongprj
  labels:
    app: ongoing-project
spec:
  selector:
    app: ongoing-project
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  type: ClusterIP
